Misc changes
lineage-next/android_packages_apps_Catapult pull request #17
Opened 2024-12-11 20:05 UTC by luca020400

- **Catapult: Remove QueryFlow.flowCursor**
- **Catapult: Migrate NetworkCallback to flows**

2024-12-14 05:31 UTC, trautamaki approved these changes
Looks good. I can't test this week though.

2024-12-14 08:58 UTC, luca020400 commented
Let's wait for you then, it's not a change I would merge without your testing :)

2024-12-16 16:54 UTC, trautamaki requested changes

2024-12-17 07:11 UTC, trautamaki approved these changes

2024-12-17 07:52 UTC, merged